---
- name: Install the php worker nodes
  hosts: app
  gather_facts: no
  become: yes
  become_method: sudo
  vars:
    remi_repo_url: "http://rpms.remirepo.net/enterprise/remi-release-6.rpm"
    remi_repo_gpg_key_url: "http://rpms.remirepo.net/RPM-GPG-KEY-remi"
    web_root: "/usr/share/nginx/html"

  tasks:
  - name: Upgrade all packages
    yum:
      name: "*"
      state: latest

  - name: Install the Remi repo
    yum:
      name: "{{ remi_repo_url }}"
      state: present

  - name: Import the Remi GPG key
    rpm_key:
      key: "{{ remi_repo_gpg_key_url }}"
      state: present

  - name: Enable epel
    yum_repository:
      name: epel
      mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch
      description: Extra Packages for Enterprise Linux 6 - $basearch
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
      gpgcheck: 1
      enabled: yes

  - name: Install libcouchbase
    yum:
      name: libcouchbase
      state: present

  - name: Install PHP cli
    yum:
      name: php70-php-cli
      state: present

  - name: Install PHP fpm
    yum:
      name: php70-php-fpm
      state: present

  - name: Install PHP couchbase2 module
    yum:
      name: php70-php-pecl-couchbase2
      state: present

  - name: Enable PHP version
    template:
      src: templates/php70.sh.j2
      dest: /etc/profile.d/php70.sh
      owner: root
      group: root
      mode: 0644
      
  - name: Fix cgi.fix_pathinfo
    lineinfile:
      dest: /etc/opt/remi/php70/php.ini
      regexp: '^cgi.fix_pathinfo=0'
      insertafter: ';cgi.fix_pathinfo=1'
      line: 'cgi.fix_pathinfo=0'

  - name: Fix fpm username
    lineinfile:
      dest: /etc/opt/remi/php70/php-fpm.d/www.conf
      regexp: '^user = '
      line: 'user = nginx'

  - name: Fix fpm group
    lineinfile:
      dest: /etc/opt/remi/php70/php-fpm.d/www.conf
      regexp: '^group = '
      line: 'group = nginx'

  - name: Fix fpm pm
    lineinfile:
      dest: /etc/opt/remi/php70/php-fpm.d/www.conf
      regexp: '^pm = '
      line: 'pm = static'

  - name: Fix fpm pm.max_children
    lineinfile:
      dest: /etc/opt/remi/php70/php-fpm.d/www.conf
      regexp: '^pm.max_children = '
      line: 'pm.max_children = 192'

  - name: Fix fpm pm.start_servers
    lineinfile:
      dest: /etc/opt/remi/php70/php-fpm.d/www.conf
      regexp: '^pm.start_servers = '
      line: 'pm.start_servers = 96'

  - name: Fix fpm pm.min_spare_servers
    lineinfile:
      dest: /etc/opt/remi/php70/php-fpm.d/www.conf
      regexp: '^pm.min_spare_servers = '
      line: 'pm.min_spare_servers = 96'

  - name: Fix fpm pm.max_spare_servers
    lineinfile:
      dest: /etc/opt/remi/php70/php-fpm.d/www.conf
      regexp: '^pm.max_spare_servers = '
      line: 'pm.max_spare_servers = 160'

  - name: Fix fpm pm.max_requests
    lineinfile:
      dest: /etc/opt/remi/php70/php-fpm.d/www.conf
      regexp: '^pm.max_requests = '
      line: 'pm.max_requests = 16384'

  - name: Enable fpm
    service:
      name: php70-php-fpm
      state: started
      enabled: true

  - name: Install the latest nginx
    yum:
      name: nginx
      state: latest

  - name: Fix server_names_hash_bucket_size
    lineinfile:
      dest: /etc/nginx/nginx.conf
      regexp: '^server_names_hash_bucket_size '
      insertafter: 'http {'
      line: 'server_names_hash_bucket_size 128;'

  - name: Fix worker_processes
    lineinfile:
      dest: /etc/nginx/nginx.conf
      regexp: '^worker_processes '
      line: 'worker_processes 24;'

  - name: Configure nginx
    template:
      src: templates/default.conf.j2
      dest: /etc/nginx/conf.d/default.conf
      owner: root
      group: root
      mode: 0644

  - name: Start nginx
    service:
      name: nginx
      state: started
      enabled: true

  - name: Upload test file
    template:
      src: templates/cache.php.j2
      dest: "{{ web_root }}/cache.php"
      owner: nginx
      group: nginx
      mode: 0755

  - name: Fix dir permissions
    file:
      path: "{{ web_root }}/"
      owner: nginx
      group: nginx
      mode: 0755
      recurse: yes
