---
- name: Install the php worker nodes
  hosts: app
  gather_facts: no
  become: yes
  become_method: sudo
  vars:
    remi_repo_url: "http://rpms.remirepo.net/enterprise/remi-release-6.rpm"
    remi_repo_gpg_key_url: "http://rpms.remirepo.net/RPM-GPG-KEY-remi"
    web_root: "/usr/share/nginx/html"

  tasks:
  - name: Upgrade all packages
    yum:
      name: "*"
      state: latest

  - name: Install the Remi repo
    yum:
      name: "{{ remi_repo_url }}"
      state: present

  - name: Import the Remi GPG key
    rpm_key:
      key: "{{ remi_repo_gpg_key_url }}"
      state: present

  - name: Enable epel
    yum_repository:
      name: epel
      mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch
      description: Extra Packages for Enterprise Linux 6 - $basearch
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
      gpgcheck: 1
      enabled: yes

  - name: Install libcouchbase
    yum:
      name: libcouchbase
      state: present

  - name: Install PHP cli
    yum:
      name: php70-php-cli
      state: present

  - name: Install PHP fpm
    yum:
      name: php70-php-fpm
      state: present

  - name: Install PHP couchbase2 module
    yum:
      name: php70-php-pecl-couchbase2
      state: present

  - name: Enable PHP
    template:
      src: templates/php70.sh.j2
      dest: /etc/profile.d/php70.sh
      owner: root
      group: root
      mode: 0644

  - name: Fix server_names_hash_bucket_size
    lineinfile:
      dest: /etc/nginx/nginx.conf
      regexp: '^server_names_hash_bucket_size '
      insertafter: 'http {'
      line: 'server_names_hash_bucket_size 128;'
      
  - name: Fix cgi.fix_pathinfo
    lineinfile:
      dest: /etc/nginx/nginx.conf
      regexp: '^cgi.fix_pathinfo=0'
      insertafter: ';cgi.fix_pathinfo=1'
      line: 'cgi.fix_pathinfo=0'

  - name: Enable fpm
    service:
      name: php70-php-fpm
      state: started
      enabled: true

  - name: Install the latest nginx
    yum:
      name: nginx
      state: latest

  - name: Configure nginx
    template:
      src: templates/default.conf.j2
      dest: /etc/nginx/conf.d/default.conf
      owner: root
      group: root
      mode: 0644

  - name: Start nginx
    service:
      name: nginx
      state: started
      enabled: true

  - name: Upload test file
    template:
      src: templates/cache.php.j2
      dest: "{{ web_root }}/cache.php"
      owner: nginx
      group: nginx
      mode: 0755
